chore: drop beta package descriptor feature, closes HYB-546
gatling/gatling-gradle-plugin pull request #104
Opened 2024-03-27 16:21 UTC by Obero

Motivation:
- Package Descriptor feature is going out of beta and v1 is coming

Modifications:
- Remove beta package descriptor deployment call from enterpriseUpload target

Result:
- Beta package descriptor: out

2024-03-27 16:24 UTC, tpetillot requested changes

2024-03-27 16:24 UTC, tpetillot commented on src/main/groovy/io/gatling/gradle/GatlingEnterpriseUploadTask.groovy
> -                packageUUID =  enterprisePlugin.uploadPackageConfiguration(jsonPackageConfig)
We need a milestone where `uploadPackageConfiguration` have been removed from commons

2024-03-27 16:26 UTC, Obero commented
I let this PR in draft until `commons` next update

2024-03-29 09:56 UTC, Obero commented
Depends on https://github.com/gatling/gatling-enterprise-plugin-commons/pull/126 release

2024-04-04 09:03 UTC, tpetillot approved these changes

2024-04-04 09:04 UTC, bastien-gatling approved these changes

2024-04-04 09:05 UTC, merged