feat: set run title and description with enterpriseStart, closes HYB-593
gatling/gatling-gradle-plugin pull request #108
Opened 2024-04-16 16:21 UTC by Obero

Motivation:
- Users want to identify their simulation runs conditions
- Users should be able to set run title and description to add metadata

Modifications:
- Pass run title and description as start operation parameters

Result:
- Run title and description can be set by users at simulation start

2024-04-16 16:21 UTC, Obero commented
In draft until this PR is released: https://github.com/gatling/gatling-enterprise-plugin-commons/pull/131

Expected commons lib version: 1.9.0

2024-04-17 18:22 UTC, Isammoc commented on src/main/groovy/io/gatling/gradle/GatlingPluginExtension.groovy
> +            }
```suggestion
            return runDescription ?: System.getProperty(RUN_DESCRIPTION_PROPERTY) ?: null
```

2024-04-18 08:23 UTC, bastien-gatling approved these changes

2024-04-19 07:44 UTC, tpetillot approved these changes

2024-04-19 07:44 UTC, tpetillot commented on src/main/groovy/io/gatling/gradle/GatlingPluginExtension.groovy
> +
```suggestion
```

2024-04-19 12:04 UTC, Isammoc requested changes

2024-04-19 12:04 UTC, Isammoc commented on src/main/groovy/io/gatling/gradle/GatlingPluginExtension.groovy
>              }
```suggestion
        String getRunTitle() {
            return runTitle ?: System.getProperty(RUN_TITLE_PROPERTY) ?: null
```

2024-04-19 12:04 UTC, Isammoc commented on src/main/groovy/io/gatling/gradle/GatlingPluginExtension.groovy
>          }
```suggestion
        String getRunDescription() {
            return runDescription ?: System.getProperty(RUN_DESCRIPTION_PROPERTY) ?: null
        }
```

2024-04-19 13:50 UTC, Isammoc approved these changes

2024-04-19 14:18 UTC, merged