chore(docs): link to demo repo
gatling/gatling-gradle-plugin pull request #12
Opened 2020-09-03 17:18 UTC by eshepelyuk

This is just a _proposal_, until the whole doc wil be migrated to Gatling docs repo.

As far as my PR to demo repo was accepted, I considered that main plugin docs ( regardless where they located) 
should be reduced a little bit.

Plz suggest.

relates gatling/gatling#3953

2020-09-03 18:57 UTC, slandelle approved these changes

2020-09-04 09:26 UTC, Isammoc requested changes
Small typo ^^

2020-09-04 09:26 UTC, Isammoc commented on README.adoc
> +and use it as a starting point for creaing your `Gatling` project.
```suggestion
and use it as a starting point for creating your `Gatling` project.
```

2020-09-04 09:28 UTC, eshepelyuk commented on README.adoc
> +and use it as a starting point for creaing your `Gatling` project.
Done, thank you

2020-09-04 09:30 UTC, Isammoc approved these changes

2020-09-04 09:30 UTC, eshepelyuk commented
@Isammoc @slandelle am I allowed to merge approved PRs ?

2020-09-04 09:38 UTC, slandelle commented
@eshepelyuk Yes, you should have the permission. Please let me know if it doesn't work.

2020-09-04 10:05 UTC, eshepelyuk commented
Well, i don't have permissions.

![image](https://user-images.githubusercontent.com/1279477/92227705-53bffd00-eeaf-11ea-920a-70ba10da7a26.png)

2020-09-04 10:16 UTC, merged

2020-09-04 10:18 UTC, eshepelyuk commented
@Isammoc thanks for merging
but my question is still open, for the future understanding

> @Isammoc @slandelle am I allowed to merge approved PRs ?

2020-09-04 10:19 UTC, Isammoc commented
Github permissions system is not flexible to let us tweak the rules as we want (at least one approval from a specific group)

So, only official mainteners (ie. GatlingCorp's employees) will have the right to merge into master.

Sorry for the inconvenience.

2020-09-04 10:20 UTC, eshepelyuk commented
> Github permissions system is not flexible to let us tweak the rules as we want (at least one approval from a specific group)
> 
> So, only official mainteners (ie. GatlingCorp's employees) will have the right to merge into master.
> 
> Sorry for the inconvenience.

Well. but I had those permissions.

![image](https://user-images.githubusercontent.com/1279477/92228999-7521e880-eeb1-11ea-91cc-25ebf042c94b.png)

2020-09-04 11:11 UTC, slandelle commented
That's my fault, sorry. I was trying to find an easy way that changes could only be committed on master through a PR. Not sure if that's feasible on Github atm. Permissions should be fixed now.

2020-09-04 11:18 UTC, eshepelyuk commented
@slandelle got it thnx.