doc: minor changes
gatling/gatling-gradle-plugin pull request #7
Opened 2020-09-01 13:35 UTC by Isammoc

2020-09-01 14:14 UTC, eshepelyuk requested changes
Could you this PR with only text changes, without any formating.
Since it's almost impossible to analyze the changes.

All formatting should be done in other PR or just directly commiting to `master`.

2020-09-01 14:14 UTC, eshepelyuk commented on README.adoc
> +== Acknowledgements
You must mention @lkishalmi as a maintainer and current plugin repository owner.

2020-09-01 22:30 UTC, eshepelyuk commented on README.adoc
> +For this quickstart: `git` must be installed and available in `$PATH`, and a JDK must be installed and `$JAVA_HOME` configured.
I have some ideas about sample project repo. Let me check first and may be i would provide a PR to it. 

@Isammoc May you add me as a collaborator to that project ?

2020-09-01 22:56 UTC, eshepelyuk commented on README.adoc
> +For this quickstart: `git` must be installed and available in `$PATH`, and a JDK must be installed and `$JAVA_HOME` configured.
Also, issues and wiki should be disabled for demo repo.

2020-09-02 08:42 UTC, Isammoc commented
@eshepelyuk 
I don't split formatting in another PR, but I separated commits. Should be easier to analyze, now.

2020-09-02 08:50 UTC, Isammoc commented on README.adoc
> +    include "**/package1/*Simu.scala"    //<1>
Yep, I confirm! (and it isn't a big change here ^^)

2020-09-02 09:01 UTC, eshepelyuk commented on README.adoc
> +    include "**/package1/*Simu.scala"    //<1>
In fact, this is a better way for callouts, according to docs.
https://asciidoctor.org/docs/user-manual/#copy-and-paste-friendly-callouts

2020-09-02 09:04 UTC, eshepelyuk commented
@Isammoc just repeating it here, seems you may missed it.

> Is it intentionnaly that this PR doesn't mention issue gatling/gatling#3940, that will be eventually closed by this PR ?

2020-09-02 09:05 UTC, eshepelyuk approved these changes

2020-09-02 09:09 UTC, eshepelyuk requested changes
@Isammoc let me explain why logn paragraphs and tables were created as multiple shorter lines instead of one big long line of text ( as you've formatted it).

This is done to improve and simplify editing of README from:

* github editor
* console editor ( like vim)

Where the visible width of the lines is usually around 80 characters. 

I'd be really appreciated if you would keep the paragraph and tables formatting as is.

2020-09-02 09:13 UTC, Isammoc commented on README.adoc
> +    include "**/package1/*Simu.scala"    //<1>
I should do it for XML as well.

2020-09-02 09:16 UTC, eshepelyuk commented on README.adoc
> +    include "**/package1/*Simu.scala"    //<1>
Yes, great idea. Thanks.

2020-09-02 09:17 UTC, Isammoc commented
@eshepelyuk 
> Where the visible width of the lines is usually around 80 characters.

When editing it, I didn't see that rule was previously followed.
But I can enforce it (I personally like it).

My point is to make the whole document consistent.

> Is it intentionnaly that this PR doesn't mention issue gatling/gatling#3940, that will be eventually closed by this PR ?

I just added a Reference in the last commit message

2020-09-02 09:19 UTC, eshepelyuk commented
> When editing it, I didn't see that rule was previously followed.
> But I can enforce it (I personally like it).
> 
> My point is to make the whole document consistent.

Yes, you're right. Was not explicitely set since I was alone working on the project :)
Let's add this to `.editorconfig` in this PR ?

> > Is it intentionnaly that this PR doesn't mention issue [gatling/gatling#3940](https://github.com/gatling/gatling/issues/3940), that will be eventually closed by this PR ?
> 
> I just added a Reference in the last commit message

Thank you !

2020-09-02 23:00 UTC, slandelle commented
The documentation of the plugin must live in the [Gatling's central documentation](https://github.com/gatling/gatling/tree/master/src/sphinx/extensions), not in the git repo's README.

Here we can have a quickstart and a link to the official documentation.

2020-09-03 08:17 UTC, eshepelyuk commented
> The documentation of the plugin must live in the [Gatling's central documentation](https://github.com/gatling/gatling/tree/master/src/sphinx/extensions), not in the git repo's README.
> 
> Here we can have a quickstart and a link to the official documentation.

ok, it's fine with me.

2020-09-03 08:18 UTC, eshepelyuk approved these changes
LGTM

2020-09-03 08:30 UTC, merged