replace deprecated -target with -release jdk version
gatling/gatling-gradle-plugin pull request #78
Opened 2023-06-21 09:02 UTC by MahatmaFatalError

I get this warning
```
compileGatlingScala
[Warn] : -target is deprecated: Use -release instead to compile against the correct platform API.
```

I hope this fixes it.

See 
https://docs.scala-lang.org/overviews/compiler-options/index.html
https://docs.gradle.org/current/userguide/upgrading_version_7.html#scala_compilation_target
https://docs.gradle.org/8.1.1/userguide/scala_plugin.html#sec:scala_target

2023-06-21 09:22 UTC, slandelle commented
Hi,

Instead, could you please remove this option? Java 8 is the default anyway and your change might break users enforcing an older Scala version.

Also, could you please [sign our CLA](https://docs.google.com/forms/u/1/d/1hbpxVqJ5hIYYJuOjOyOzub9fJFGFGvvfnB5w5LCWdUw/edit)?

2023-06-21 09:23 UTC, slandelle requested changes
Actually, please remove the whole line.

2023-06-25 20:52 UTC, slandelle commented
> Also, could you please [sign our CLA](https://docs.google.com/forms/u/1/d/1hbpxVqJ5hIYYJuOjOyOzub9fJFGFGvvfnB5w5LCWdUw/edit)?

@MahatmaFatalError up

2023-06-28 13:03 UTC, slandelle commented
@MahatmaFatalError gentle ping

2023-06-29 11:28 UTC, MahatmaFatalError commented
> @MahatmaFatalError gentle ping

I signed ✍️

2023-06-29 12:17 UTC, slandelle approved these changes

2023-06-29 12:18 UTC, merged

2023-06-29 12:18 UTC, slandelle commented
Perfect, thanks!

2023-06-29 12:21 UTC, slandelle commented
Just released 3.9.5.1